name: Package Module (Tag)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: |
          zip -r rebuildconnector.zip rebuildconnector/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rebuildconnector-zip
          path: rebuildconnector.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: rebuildconnector.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
